### ISSUE TITLE
update all pressbooks plugins for development

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-cc-export#1]
we have to develop against the latest

**Comment by alex-418** [comment]
@bdolor Updated pressbooksdev and opentextbcdev WP Core and Plugins. Everything looks/works good.

**Comment by lucwrite** [comment]
I am stuck on validating this because we can't get my VPN working and so I can't get on PB Dev. I will try again to fig out on Wed

**Comment by lucwrite** [comment]
Ok I have validated this on both dev servers everything working well. All of the features have been checked up to PB 4.4.0 and all plugins checked
