### ISSUE TITLE
Create a v1.1 compatible export file

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-cc-export#10]
As a standalone plugin, build an export routine that creates a `.imscc` file that can be imported into Moodle.

**Comment by bdolor** [comment]
The export routine works, minimally, producing a v1.1 imscc file which can be imported into Moodle. With no file icon at the PB export page, it requires that you hover around where you think it might be until the download icon appears. 

There is some clean up with the HTML to do (double titles, for instance), and some discovery around why images don't import (could just be my local development environment). Images are contained within the file and referenced accordingly, so also could just be a moodle thing. 

Either way, I'll keep this in the 'Doing' column for now and ask that it be validated after I've had a chance to look at these issues. All changes are deployed and available on the dev server. 

![image](https://user-images.githubusercontent.com/2048170/33150940-a22eaa64-cf8a-11e7-97ad-e6fb14830813.png)

![image](https://user-images.githubusercontent.com/2048170/33150975-cf875452-cf8a-11e7-892b-3cdb4d7119ab.png)

**Comment by bdolor** [comment]
@lucwrite - this ready for validation but I'd like to work with you today re: importing of images on the Moodle side — by all known theoretical means, the images and html are placed in the zip/imscc directory as expected by my understanding of v1.1 standard.  

![image](https://user-images.githubusercontent.com/2048170/33186922-821e8632-d042-11e7-931e-00d9fc818930.png)

Despite these efforts, images don't come in on my local instance of Moodle. This could be isolated to my dev environment, or it could be something that Moodle wants that we're not giving it. Could you please see if you can recreate this on your instance of Moodle? Then I can look at it more closely.

**Comment by lucwrite** [comment]
I am in a meeting but just after 1:00 will pull the CC is our Moodle dev environment. Will be around all afternoon for this as well

**Comment by bdolor** [comment]
Can confirm that the zip process duplicates files unnecessarily. Doubles the size of the file and clutters things up. Will be looking at a solution to this.

![image](https://user-images.githubusercontent.com/2048170/33190641-adc38050-d063-11e7-8380-5d40bc3b941e.png)

**Comment by lucwrite** [comment]
So a couple things I have been testing 

In addition to the Restore Import you can import in as an IMS content package within the course. This does display the images and creates a navigatable frame
 Moodle has a book function that also accepts IMS packages as well as HTML zips. However, this does not bring in the images.

**Comment by bdolor** [comment]
wow that's really large font

**Comment by lucwrite** [comment]
Yeah I think I fixed it. Was using # to rep numbers in this markup = large font

**Comment by bdolor** [comment]
duplicate file issue has been resolved via https://github.com/BCcampus/pressbooks-cc-export/commit/e4e2316974256d1ec437f9a4423a46406e22918a

**Comment by bdolor** [comment]
So, as far as images go, are you satisfied that this is working as expected, or should we continue to investigate?

**Comment by lucwrite** [comment]
I think we should continue to investigate as we should be able to upload into the book as pages and IMS module has a fairly small frame and editing,limitations

**Comment by bdolor** [comment]
For clarification, there are three import processes in Moodle?

1. Restore Import
2. Import IMS in a course
3. Book plugin Import

So far,  Import IMS in a course is the one that works as expected?

**Comment by lucwrite** [comment]
1. Restore Import (Course level) Imports as pages -- images not working
2. IMS Package Imports as an IMS Package (Frame with HTLM Pages and a TOC on the side) -- images work
3. Book Imports by Chapter --images not working. Also imports HTML Zip

**Comment by bdolor** [comment]
As far as I can tell, '_Book Import by Chapter_' wants nothing more than a flat, unorganized zip file with html files and images/media...no index/manifest required. As an unintended consequence of duplicating all image/html files at the root of the imscc file, the _Book Import_ by chapter worked, though the the relative links in the html files at the root of the directory are pointed at an images/assets directory which doesn't exist. I think that explains the reason the images don't display for that import routine. Now that the file duplication is fixed, my guess is that the _Book Import_ will not work at all. 

It's only if the _Book Import_ paid attention to/cared about the `imsmanifest.xml ` would it be able to find/import the correct html files (in OEBPS directory) that have the correct relative path to the images directory which _does_ exist. At first blush it would seem to me that while the Book Import feature may be a valid use case, it's not the target we were aiming for in this particular sprint.

**Comment by lucwrite** [comment]
I understand re the Book Importer. Let me know when I can test another export with the changes you have made. If the book does not work, it would be ideal to pull image files into the course import. Restore course. This is one way documented in Moodle docs to pull in an IMS package. The downside of using the IMS Package course tool is that it is a very small frame and it is not editable.

**Comment by bdolor** [comment]
Deployment of the dev branch to the dev server is instantaneous.

**Comment by bdolor** [comment]
I will look at the Pages module inside 'Restore Course', though if it ends up that we are giving Moodle a valid IMS file the problem may be with Moodle rather than anything else we can do within the scope of a 1.1 Common Cartridge spec.

**Comment by lucwrite** [comment]
Your assumption is correct re uploading to the book importer. This no longer works, the error is that chapter are missing. Import works as Restore--> Pages with no images. (Export 9:15am)

**Comment by bdolor** [comment]
@lucwrite — Is there an example of a cc 1.1 file with embedded images that does work with the Restore Import process?

**Comment by lucwrite** [comment]
Ok here it is. 

[backup-moodle2-course-4-lucastest-20171124-1952-nu.zip](https://github.com/BCcampus/pressbooks-cc-export/files/1502478/backup-moodle2-course-4-lucastest-20171124-1952-nu.zip)

**Comment by bdolor** [comment]
maybe solved via https://github.com/BCcampus/pressbooks-cc-export/commit/76448838fe570ec9012caf6733ef0de98acf9bbd

**Comment by bdolor** [comment]
closing
