### ISSUE TITLE
Local dev enviro setup

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks-cc-export#11]

**Comment by alex-418** [comment]
PHP 7 
Moodle Latest version (3.4) 
Latest version of PB/PBtextbook etc

**Comment by alex-418** [comment]
Ran into an issue with the latest weekly stable release, after creating the database and running through the installation successfully, the website displays the following error: `Coding error detected, it must be fixed by a programmer: PHP catchable fatal error` despite passing the requirements check during installation. The only one that was missing was opcache (although it's not required), and I've ensured opcache is enabled on my server, and configured php.ini as per the [documentation](https://docs.moodle.org/34/en/OPcache). I've enable debugging in my Moodle config, but it's not providing any more output for a clue as to why it's not working.

**Comment by bdolor** [comment]
closing
