### ISSUE TITLE
Update production server PB/Themes/Plugins

### ISSUE THREAD

**Issue by alex-418** [BCcampus/pressbooks-cc-export#13]
New versions of PB includes new features

**Comment by clintlalonde** [comment]
Wordpress 4.9 Update Notes https://wordpress.org/news/2017/11/tipton/

**Comment by alexpflores** [comment]
@bdolor Updated pressbooksdev and opentextbcdev WP Core and Plugins.

**Comment by bdolor** [comment]
please use https://github.com/BCcampus/pressbooks-cc-export/issues/1 to report on that

**Comment by bdolor** [comment]
Will update Friday morning (early)

**Comment by bdolor** [comment]
this has been done, @lucwrite ready for validation
