### ISSUE TITLE
Increase php.ini on Moodle site

### ISSUE THREAD

**Issue by clintlalonde** [BCcampus/pressbooks-cc-export#15]
Upload limit on Moodle test site is set at 2M. Need to increase to accomodate larger CC file sizes.

**Comment by BCcampusMgt** [comment]
Ben at SFU changed moodlebox.bccampus.ca (Terri) php.ini settings:
post_max_size = 8M   to
post_max_size = 50M

upload_max_filesize = 2M   to
upload_max_filesize = 50M

**Comment by bdolor** [comment]
closing
