### ISSUE TITLE
CSS support for display of icons

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-cc-export#16]
A theme independent injection of CSS (and supporting icons) in the admin dashboard on the export page and on the homepage of any theme

**Comment by alex-418** [comment]
Completed via #17 and #18. 

**Admin Icon:**
![screen shot 2017-11-23 at 3 24 32 pm](https://user-images.githubusercontent.com/17072191/33190588-1592d7b8-d063-11e7-9394-396804f13b33.png)

**Book   Icon:** 
![screen shot 2017-11-23 at 3 24 24 pm](https://user-images.githubusercontent.com/17072191/33190589-15a6ee4c-d063-11e7-92d5-e1692401a1e7.png)
