### ISSUE TITLE
Create a Version 1.1 CC export for Canvas

### ISSUE THREAD

**Issue by lucwrite** [BCcampus/pressbooks-cc-export#21]
###Creating a IMS 1.1 Common Cartridge export that imports into Canvas as a "attachment" instead of "Page" or "WikiPage" This will allow for the imported OTB to be edited in Canvas LMS. Within Canvas currently "attachment" html needs to be externally edited.

### System Information

- Pressbooks CC Export: [Enter PCE Version here] 
- Pressbooks: [4.4.0] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
Would like to eliminate the possibility that this would speak more to a limitation of the Canvas import functionality than something else we can do to the CC package within the 1.1 spec. If there is a certain file that you know works, that might be a good place to start.
