### ISSUE TITLE
Adding (Beta) to the Common Cartridge Export (Enhancement)

### ISSUE THREAD

**Issue by lucwrite** [BCcampus/pressbooks-cc-export#22]
### Description 

Due to the language change from "Exotic Formats" to "Other Formats" for exports type in 4.5.0 changing the CC Export to Common Cartridge( v1.1) to Common Cartridge 1.1 (beta). This will also match EPUB 3 (beta) ] The purpose of this is to manage user expectations when using CC export at this time with different Learning Management Systems.

### System Information

- Pressbooks CC Export: [0.1.0] 
- Pressbooks: [4.5.0] 
- WordPress: [4.9.1]

**Comment by bdolor** [comment]
closing
