### ISSUE TITLE
CC download link not displayed well with pressbooks-book 2.0 rc-2 

### ISSUE THREAD

**Issue by beckej13820** [BCcampus/pressbooks-cc-export#25]
### Description 

With the new default book layout in Pressbooks 5.0, CC exports are shown as a long broken link.

**Expected behaviour** 

Link says "Common Cartridge" or equivalent
 
**Actual behaviour** 

In the new dropdown menu, CC appears as 
Notice: Undefined index: imscc11 in /var/www/html/wp-content/themes/pressbooks-book/inc/helpers/namespace.php on line 62

### Steps to reproduce the problem

Install PB 5 with the new pressbooks-book theme mcluhan. 

### System Information

- Pressbooks CC Export: 0.1.0-RC1
- Pressbooks: 5.0.0-rc.1 
- WordPress: 4.9.4
![screen shot 2018-02-22 at 9 12 45 pm](https://user-images.githubusercontent.com/29982981/36574756-35584afc-1815-11e8-9ffe-2ee92aba4fad.png)

**Comment by greatislander** [comment]
Hi @bdolor, added a filter to help with this in https://github.com/pressbooks/pressbooks-book/commit/fd7bf2d7f909d39656d053bf228236dd73f9e0ac.

(In Book 2.0/McLuhan, we are using a text dropdown instead of icons for downloadable files.)

**Comment by bdolor** [comment]
thank you both, will look into this.

**Comment by bdolor** [comment]
should be resolved with https://github.com/BCcampus/pressbooks-cc-export/commit/7f2985694da2a5e46e70cef8f83b5105679646df please try https://github.com/BCcampus/pressbooks-cc-export/releases/tag/0.2.0-rc.1
