### ISSUE TITLE
change file_put_contents to wp filesystem methods

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-cc-export#29]
### Description 

best practice is to use wp methods and phpcs generates a half dozen warnings around `file_put_contents()`

**Expected behaviour** 

running `vendor/bin/phpcs` should generate no warnings, and code should be refactored to benefit from wp methods.

**Actual behaviour** 

Warnings: `File operations should use WP_Filesystem methods instead of direct PHP filesystem calls.`

### Steps to reproduce the problem

run `composer standards` to surface warning messages

### System Information

- Pressbooks CC Export: [0.2.3] 
- Pressbooks: [5.4.0] 
- WordPress: [4.9.7]

**Comment by greatislander** [comment]
@bdolor see: https://github.com/pressbooks/pressbooks/blob/dev/inc/utility/namespace.php#L1225-L1319

Some of these may be useful. We did this to conform to coding standards.

**Comment by bdolor** [comment]
interesting...thanks for pointing that out.
