### ISSUE TITLE
investigate common cartridge validation options

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-cc-export#4]
investigate if there is a common cartridge validation that can be used to ensure compliance along with export

**Comment by alex-418** [comment]
Might have to be a member of IMS global

**Comment by clintlalonde** [comment]
Clint can contact network to find validator

**Comment by alex-418** [comment]
Mary: 

> If we need a membership it's not too expensive
> https://www.imsglobal.org/cc/jointhealliance.cfm
> looks like $750 bucks US for us - I'm happy to pay for that if we end up needing it.

**Comment by alex-418** [comment]
Preference on open source solution, instead of proprietary solution that requires membership

**Comment by clintlalonde** [comment]
Posted question in IMS Global CC forum https://www.imsglobal.org/forum/common-cartridge-public-forum/158341

**Comment by bdolor** [comment]
Confirmed that IMS validation is a membership only service, which seems counterintuitive to having an open standard. At any rate validation using that service doesn't/won't integrate into an export routine. 

A more programmatic solution might be found in looking at the ways that the import routine from moodle or another LMS validates what type of file it's dealing with, for example:  https://github.com/moodle/moodle/blob/master/backup/cc/validator.php
