### ISSUE TITLE
get a v1.1 file 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-cc-export#5]
have an example file that we can work from that we know works

**Comment by lucwrite** [comment]
Places to get file http://www.skillscommons.org, Open learn UK http://www.open.edu/openlearn/free-courses/full-catalogue

**Comment by lucwrite** [comment]
Still trying to find suitable file for V1. Need to know how to identify versus 1.1 versus 1.0, 1.2

**Comment by alex-418** [comment]
Validate file to ensure it works (validation tool?)

**Comment by clintlalonde** [comment]
Find a validator

**Comment by clintlalonde** [comment]
This is a simple course file that might work. Looks like only html and images. http://www.open.edu/openlearn/history-the-arts/history/heritage/aberdulais-falls-case-study-welsh-heritage/content-section-0?active-tab=description-tab

**Comment by lucwrite** [comment]
Having difficulty finding V 1.1 file. All OpenLearning is 1.0. Canvas Commons = 1.3. Canvas does export 1.1. What are your thoughts on copying an opentext into a canvas course and exporting as 1.1.imscc?

**Comment by lucwrite** [comment]
[test-common-cartidge-export.zip](https://github.com/BCcampus/pressbooks-cc-export/files/1489365/test-common-cartidge-export.zip)

**Comment by lucwrite** [comment]
Hi @bdolor and @alexpflores and @clintlalonde I was unable to find a CC 1.1. Instead I copied a chapter of Teaching in a Digital Age into Canvas and exported it. Canvas exports as V1.1. Will this be enough for you to work with? I was succesfully able to upload the file into Moodle.

**Comment by lucwrite** [comment]
If we want something more complex, I can import a course from Canvas Commons  (All courses in commons are V 1.3) and then export it from the Canvas course (Exports are 1.1). I could also build a more complex course and include elements that you would like me to add and export. Let me know if this works

**Comment by bdolor** [comment]
there is quite a difference between the file structures of the 1.1 file exported from Canvas and the 1.0 file from open.edu 

*1.0*
![image](https://user-images.githubusercontent.com/2048170/33045504-dd9d45e0-ce01-11e7-91fa-c1895f08092f.png)

*1.1*
![image](https://user-images.githubusercontent.com/2048170/33045522-f51ef16e-ce01-11e7-9bc7-728000911f62.png)

seems to include a directory of `course_settings` — would be good to know if this is a 1.1 requirement or something that Canvas has added as a flavour.

**Comment by bdolor** [comment]
My suspicion is that this is a 'Canvas' interpretation of 1.1.

**Comment by lucwrite** [comment]
I am exporting a Blackboard course into 1.1 now so that you can compare. Although I wouldn't be suprised if BB adds its own flavour, usually not a good one.

**Comment by lucwrite** [comment]
[CommonCartridge_TechRoversOnlineOrientation_20171120032134.zip](https://github.com/BCcampus/pressbooks-cc-export/files/1489462/CommonCartridge_TechRoversOnlineOrientation_20171120032134.zip)

**Comment by lucwrite** [comment]
This is a simple course outputted as 1.1 from Blackboard. I have not tried to pull it into Moodle yet. I am waiting for the file upload size to be changed by George

**Comment by bdolor** [comment]
reopening ticket, assuming it was closed in error.

**Comment by lucwrite** [comment]
Thanks sorry bout that

**Comment by lucwrite** [comment]
[CommonCartridge_TechRoversOnlineOrientation_20171120032134.zip](https://github.com/BCcampus/pressbooks-cc-export/files/1489473/CommonCartridge_TechRoversOnlineOrientation_20171120032134.zip)

**Comment by lucwrite** [comment]
This is an example of a simple course exported from Blackboard as V 1.1 CC. I have not tried to import it into Moodle yet, as George will be adjusting the file size upload limit from 2 MB

**Comment by lucwrite** [comment]
I do not see the course settings folder.

**Comment by bdolor** [comment]
After looking at the variety of file structure that these three files present, it leaves me with the impression that either 
1. implementing a valid 1.1 file is pretty loose, more like a guideline rather than an actual standard
2. the vendors don't particularly care about compliance
3. the contradiction of having an open standard and keeping validation tools behind a paywall encourages complacency.

**Comment by lucwrite** [comment]
This is what the validator used to look like https://web.archive.org/web/20150924151217/http://validator.imsglobal.org/  Now a dead link.

**Comment by lucwrite** [comment]
That was only a year ago so I am going to guess 1 or 2 above is correct.

**Comment by bdolor** [comment]
The forum doesn't seem to be a hotbed of activity: https://www.imsglobal.org/forum/common-cartridge-public-forum/145531

**Comment by lucwrite** [comment]
Ok was wondering late last night., if some of the difference you are seeing with CCs files is due to the exported course structure. The Blackboard course was a complex course the Canvas course was simple. Here is a Moodle course with approximately the same content as the Canvas course. Basically, I have copy and pasted in some HTML pages from Teaching in a Digital Age and also created a module (Canvas) and a lesson plan (Moodle). These are basically pages of content connected together with Navigation. Canvas, Blackboard all export as 1.1. Let me know what you to complete this task. I can either create one or import a course into all three systems and export it. Or maybe the three CCs I have provided are enough
[backup-moodle2-course-4-lucastest-20171121-1634-nu.zip](https://github.com/BCcampus/pressbooks-cc-export/files/1492178/backup-moodle2-course-4-lucastest-20171121-1634-nu.zip)

**Comment by bdolor** [comment]
What I think there is to learn from the variety of file structures presented in these flavours is that the standard for 1.1 is much more loose in its implementation, which is to say that there still are ways to make a file non-compliant but as far as file structure goes it seems to be different than what the requirements are for meeting an EPUB2, DOCX or ODT standard, for instance. In each of these standards there are strict naming conventions and as far as I can tell there isn't the same expectation in CC. 

The most substantial piece of evidence that would support that notion is the three different examples they give of compliant file structures in a v1.1 document. Here is one example:

![image](https://user-images.githubusercontent.com/2048170/33085636-0c5625ee-ce9a-11e7-9192-4f54f41ce9f6.png)

**Comment by lucwrite** [comment]
Can we close this or do we need more CC files to compare?

**Comment by bdolor** [comment]
As far as any more work to be done on it, I think it's safe to say we've covered due diligence. In the context of the sprint, removing your assignment and moving it over to the validating column would suffice.

**Comment by lucwrite** [comment]
Ok one note:  The Canvas version of 1.1 in testing seems easier to consume by Moodle than the Blackboard CC. I had a fatal error trying to bring the BB common cartridge into Moodle, but was able to import a complex course from Canvas to Moodle with no errors.
