### ISSUE TITLE
access to a moodle development instance 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-cc-export#6]
we need this up and give access to all testers/developers

**Comment by lucwrite** [comment]
https://cceducation.moodlecloud.com/   

Login: Admin
Will share password

**Comment by lucwrite** [comment]
Note: I am finding Moodle is a difficult platform to test CC in. One error in CC = process failure. In Canvas same CCs were able to be uploaded with multiple errors.

**Comment by lucwrite** [comment]
https://moodlebox.bccampus.ca/login/index.php Clint has contacted Brian/George to set up

**Comment by clintlalonde** [comment]
I have an admin account for Moodle testing server. I created a user account for Lucas and a dummy course shell to test CC imports against.

**Comment by clintlalonde** [comment]
Upload limit changed from 2MB to 50MB. @lucwrite

**Comment by lucwrite** [comment]
Awesome, not to try out a couple CCS

**Comment by alex-418** [comment]
@clintlalonde or @lucwrite can we get admin accounts on this pls?
