### ISSUE TITLE
file icons for the export 

### ISSUE THREAD

**Issue by bdolor** [BCcampus/pressbooks-cc-export#7]
imscc need their own icons

![image](https://user-images.githubusercontent.com/2048170/32973207-13f39d82-cbab-11e7-969d-9da69a110197.png)

**Comment by alex-418** [comment]
Need the sizes and file format

**Comment by lucwrite** [comment]
Lucas will contact Robyn about this.

**Comment by lucwrite** [comment]
Requested this to Barb and Robyn size = 48px x 48px

**Comment by bdolor** [comment]
https://github.com/pressbooks/pressbooks/tree/dev/assets/src/images 

there are 4 dimensions used: 
- 36x36
- 48x48
- 72x72
- 96x96

**Comment by lucwrite** [comment]
Thanks just followed up with marketing.

**Comment by lucwrite** [comment]
Marketing confirms that they have added this to the production schedule and expect to be able to creat icon next Wed Nov 29th.

**Comment by lucwrite** [comment]
They have asked if we have a colour preference? I don't and can leave it up to them but please comment if you have a preference.

**Comment by bdolor** [comment]
Perhaps not using a colour that's already represented by other file formats is a good limitation to work within.

**Comment by lucwrite** [comment]
Robyn has created a purple icon to create a different color category. We have used CC 1.1 for the wording. Please let me know if this works and whether she should just email you the files or if there is another space for them to be uploaded to.

**Comment by alex-418** [comment]
@lucwrite please upload here and I'll add them to #16 so I can wrap that one up! tnx

**Comment by lucwrite** [comment]
![cc-36](https://user-images.githubusercontent.com/19966949/33190450-c6108394-d061-11e7-92db-c4d2df57d
![cc-72](https://user-images.githubusercontent.com/19966949/33190453-c98727c6-d061-11e7-80fb-2a4305f175e4.png)
![cc-96](https://user-images.githubusercontent.com/19966949/33190455-caaa9340-d061-11e7-9530-3f9e15c9e717.png)

878.png)
![cc-48](https://user-images.githubusercontent.com/19966949/33190451-c78015fa-d061-11e7-856b-1d189a67b314.png)

**Comment by lucwrite** [comment]
[cc-36](https://user-images.githubusercontent.com/19966949/33190461-d158e584-d061-11e7-9558-aeed8c48b3ab.png)

**Comment by lucwrite** [comment]
![cc-96](https://user-images.githubusercontent.com/19966949/33190470-eaf778c0-d061-11e7-95d3-e790effd0625.png)
![cc-72](https://user-images.githubusercontent.com/19966949/33190471-ec68f01c-d061-11e7-8190-dc0186035198.png)
![cc-48](https://user-images.githubusercontent.com/19966949/33190472-ee7d7fda-d061-11e7-9d76-dc57e8e5d94e.png)
![cc-36](https://user-images.githubusercontent.com/19966949/33190473-ef97b03e-d061-11e7-9b88-64b82207e35f.png)
